"""Cabinets conseiller financier — Outscraper SDK + keyword gate (no Pappers / no website enrich)."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "cabinets_conseiller_financier"
PRESET_LABEL = "Cabinets conseiller financier (France)"

_LIST_ID = "4a616678-06a0-44d2-a27c-f9248a4c34bf"
_CAMPAIGN_ID = "e3bdb573-fe9f-437d-bd96-4ceb52869dd4"
_SUBSEQUENCE_ID = "d656122e-fb42-42ac-a8c9-324eb9a13b86"

_COMPTABLE_VOL_LIST_ID = "ca3e72d4-5a43-4399-a89b-566095e69c25"

CABINETS_CONSEILLER_FINANCIER_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_SUBSEQUENCE_ID": _SUBSEQUENCE_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [
        _LIST_ID,
        _COMPTABLE_VOL_LIST_ID,
    ],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [],
    "INSTANTLY_SKIP_IF_IN_CAMPAIGN": True,
    "INSTANTLY_SKIP_IF_IN_LIST": True,
    "INSTANTLY_PUSH_EVERY": 25,
    "INSTANTLY_BACKLOG_PUSH_MIN": 25,
    "INSTANTLY_PROVISION_LINKS": True,
    "LINK_PROVISION_CATEGORY": "cif",
    "ENRICH_ENABLED": False,
    "WEBSITE_REQUIRED": False,
    "OUTSCRAPER_FILTERS": ["operational_only"],
    "TAXONOMY_GATE_ENABLED": True,
    "TAXONOMY_MATCH_MODE": "taxonomy_only",
    "TAXONOMY_INCLUDED_KEYWORDS": [
        "conseiller financier",
        "financial consultant",
        "financial planner",
        "planificateur financier",
        "gestion de patrimoine",
        "gestionnaire de patrimoine",
        "conseiller en investissements financiers",
        "conseil en investissement",
        "courtier en placement financier",
        "investment service",
        "wealth management",
        "cgp",
        "cgpi",
        "cif",
        "intermédiaire en assurance",
        "courtier en assurance",
        "courtier d'assurances",
    ],
    "TAXONOMY_EXCLUDED_KEYWORDS": [
        "crédit agricole",
        "bnp paribas",
        "société générale",
        "banque populaire",
        "caisse d'épargne",
        "axa",
        "fortuneo",
        "linxea",
        "mutuelle",
        "lcl",
        "boursorama",
        "bforbank",
        "banque",
        "bank",
        "restaurant",
        "école",
        "ecole",
        "business school",
        "université",
        "avocat",
        "notaire",
        "agence immobilière",
        "agence immobiliere",
        "immobilier",
        "real estate",
        "expert immobilier",
        "agent immobilier",
        "gestionnaire de patrimoine immobilier",
        "société de gestion immobilière",
        "hypothécaire",
        "mortgage",
        "courtier en prêts",
        "expert-comptable",
        "expert comptable",
        "expertise comptable",
        "comptable",
        "automobile",
        "auto broker",
        "garage",
        "agence d'assurance",
    ],
    "ENRICH_INCLUDED_KEYWORDS": [],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 16,
    "OUTSCRAPER_LIMIT_PER_QUERY": 200,
    "OUTSCRAPER_POLL_INITIAL_S": 10,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 12,
    "OUTSCRAPER_ENRICHMENT": ["leads_n_contacts"],
    "OUTSCRAPER_EMAIL_RECOVERY_ENABLED": True,
    "TARGET_LEADS": 3000,
    "TARGET_MODE": "instantly_pushed",
    "SCRAPE_START_QUERY_PASS": 1,
    "SCRAPE_SKIP_PHASE_ENABLED": False,
    "SCRAPE_SKIP_SATURATION_TO_DEPARTMENT": True,
    "DUPLICATE_GEO_ADVANCE_RATE": 0.50,
    "SCRAPE_RELOAD_ENABLED": True,
    "SCRAPE_RELOAD_MAX_ROUNDS": 8,
    "SCRAPE_RELOAD_START_GEO_PHASE": "pass",
    "SCRAPE_RELOAD_START_QUERY_PASS": 1,
    "SCRAPE_CONTINUOUS_MODE": True,
    "SCRAPE_CONTINUOUS_MAX_ZERO_CYCLES": 3,
    "CONTINUOUS_KEYWORD_ROTATIONS": [
        [
            "conseiller patrimoine",
            "cabinet gestion patrimoine",
            "cgpi",
            "courtier en assurance vie",
        ],
        [
            "conseiller en investissements financiers",
            "cabinet cif",
            "gestion privée",
            "family office",
        ],
        [
            "planificateur financier",
            "conseil en gestion de patrimoine",
            "intermédiaire en assurance",
            "cabinet conseil financier",
        ],
        [
            "optimisation patrimoniale",
            "conseiller financier indépendant",
            "cgp indépendant",
            "courtier assurance",
        ],
    ],
    "SERVICE_DEFAULT": "Gestion de patrimoine",
    "SERVICE_RULES": [],
    "KEYWORDS": [
        "conseiller gestion patrimoine",
        "cabinet conseiller financier",
        "CGP",
        "CGPI",
        "CIF",
        "courtier assurance",
        "gestion de patrimoine",
    ],
    "EXPANSION_KEYWORDS": [
        "conseiller en investissements financiers",
        "courtier en assurance",
        "cabinet patrimoine",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": False,
    "NICHE_METADATA": {
        "angle": "Lead gen pour cabinets conseiller financier",
        "valeur_client": "Prise de RDV avec des cabinets CGP / CIF / courtiers",
        "effectif_cible": "qualif à la réponse",
    },
}

CONFIG = CABINETS_CONSEILLER_FINANCIER_CONFIG
