"""Médecine esthétique (France) — Outscraper taxonomy gate."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "medecine_esthetique"
PRESET_LABEL = "Médecine esthétique (France)"

INSTANTLY_NAME = "Médecin esthétique"
SCRAPE_QUEUE_RANK = 2

_LIST_ID = "cb28cf8a-d94d-4764-bc47-50fc1407417f"
_CAMPAIGN_ID = "a63b69d0-5eef-48b8-b38d-ad875b8df917"
_SUBSEQUENCE_ID = ""

MEDECINE_ESTHETIQUE_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_NAME": INSTANTLY_NAME,
    "SCRAPE_QUEUE_RANK": SCRAPE_QUEUE_RANK,
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_SUBSEQUENCE_ID": _SUBSEQUENCE_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_SKIP_IF_IN_CAMPAIGN": False,
    "INSTANTLY_SKIP_IF_IN_LIST": False,
    "INSTANTLY_PUSH_EVERY": 25,
    "INSTANTLY_PROVISION_LINKS": False,
    "ENRICH_ENABLED": False,
    "INGESTER_ENABLED": True,
    "INGESTER_MIN_SCORE": 0.55,
    "INGESTER_BORDERLINE_MIN": 0.35,
    "INGESTER_CONCURRENCY": 12,
    "INGESTER_FETCH_TIMEOUT": 8.0,
    "INGESTER_SIGNAL_WEIGHTS": {
        "taxonomy": 0.35,
        "website": 0.30,
        "review": 0.20,
        "registry": 0.15,
    },
    "INGESTER_REVIEW_ICP_KEYWORDS": [
        "esthétique",
        "esthetique",
        "injections",
        "laser",
        "anti-âge",
        "botox",
        "consultation",
        "soins",
    ],
    "INGESTER_REVIEW_ANTI_ICP_KEYWORDS": [
        "logiciel",
        "plateforme",
        "recrutement",
        "pharmacie",
        "dentaire",
        "vétérinaire",
    ],
    "OUTSCRAPER_FILTERS": ["only_with_website", "operational_only"],
    "TAXONOMY_GATE_ENABLED": True,
    "TAXONOMY_INCLUDED_KEYWORDS": [
        "médecine esthétique",
        "medecine esthetique",
        "clinique esthétique",
        "clinique esthetique",
        "centre esthétique",
        "centre esthetique",
        "centre laser",
        "institut esthétique",
        "institut esthetique",
        "aesthetic clinic",
        "medical spa",
        "spa médical",
        "medical spa",
        "skin care clinic",
        "soins esthétiques",
        "soins esthetiques",
        "laser hair removal",
        "épilation laser",
        "epilation laser",
        "cosmetic surgeon",
        "chirurgien esthétique",
        "chirurgien esthetique",
        "dermatologue",
        "dermatology clinic",
    ],
    "TAXONOMY_EXCLUDED_KEYWORDS": [
        "dentiste",
        "dentaire",
        "chirurgien-dentiste",
        "pharmacie",
        "médecin généraliste",
        "medecin generaliste",
        "hôpital",
        "hopital",
        "vétérinaire",
        "veterinaire",
        "coiffeur",
        "salon de coiffure",
        "institut de beauté",
        "institut de beaute",
        "recrutement",
        "logiciel médical",
    ],
    "ENRICH_INCLUDED_KEYWORDS": [
        "esthétique",
        "esthetique",
        "médecine esthétique",
        "laser",
        "injections",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "dentaire",
        "pharmacie",
        "recrutement",
        "logiciel",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 2,
    "OUTSCRAPER_LIMIT_PER_QUERY": 400,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "OUTSCRAPER_ENRICHMENT": ["leads_n_contacts"],
    "OUTSCRAPER_EMAIL_RECOVERY_ENABLED": True,
    "TARGET_LEADS": 3000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Médecine esthétique",
    "SERVICE_RULES": [],
    "KEYWORDS": [
        "médecine esthétique",
        "clinique esthétique",
        "centre laser",
    ],
    "EXPANSION_KEYWORDS": [
        "medecine esthetique",
        "clinique esthetique",
        "injections acide hyaluronique",
        "aesthetic clinic",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": False,
    "NICHE_METADATA": {
        "angle": "Patients récurrents (injections) ; décision rapide ; budget un peu plus serré",
        "valeur_client": "Prise de RDV consultations injections, laser, soins anti-âge",
        "effectif_cible": "cabinets et cliniques indépendants",
        "priorite": 2,
    },
}

CONFIG = MEDECINE_ESTHETIQUE_CONFIG
