"""Médecins généralistes (France) — Outscraper taxonomy gate, JUM link provision."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "medecins_generalistes"
PRESET_LABEL = "Médecins généralistes (France)"

_LIST_ID = "7e3b619f-9823-4d64-bc50-31f01bb08e6d"
_CAMPAIGN_ID = "5c142a13-fcdf-4d6d-92e7-2afbc1865a5a"
_SUBSEQUENCE_ID = ""

_DENTISTE_LIST_ID = "d97775c2-8708-40a6-9cb8-5844da8d2e0d"

MEDECINS_GENERALISTES_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_SUBSEQUENCE_ID": _SUBSEQUENCE_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [
        _LIST_ID,
        _DENTISTE_LIST_ID,
    ],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [],
    "INSTANTLY_SKIP_IF_IN_CAMPAIGN": True,
    "INSTANTLY_SKIP_IF_IN_LIST": True,
    "INSTANTLY_PUSH_EVERY": 25,
    "INSTANTLY_BACKLOG_PUSH_MIN": 25,
    "INSTANTLY_PROVISION_LINKS": True,
    "LINK_PROVISION_CATEGORY": "jum",
    "ENRICH_ENABLED": False,
    "WEBSITE_REQUIRED": False,
    "OUTSCRAPER_FILTERS": ["operational_only"],
    "TAXONOMY_GATE_ENABLED": True,
    "TAXONOMY_MATCH_MODE": "taxonomy_only",
    "TAXONOMY_INCLUDED_KEYWORDS": [
        "médecin généraliste",
        "medecin generaliste",
        "general practitioner",
        "family doctor",
        "médecin de famille",
        "medecin de famille",
        "médecin traitant",
        "medecin traitant",
    ],
    "TAXONOMY_EXCLUDED_KEYWORDS": [
        # Spécialistes
        "cardiologue",
        "dermatologue",
        "gynécologue",
        "gynecologue",
        "ophtalmologue",
        "pédiatre",
        "pediatre",
        "psychiatre",
        "chirurgien",
        "dentiste",
        "dentaire",
        "orthodontiste",
        # Structures
        "hôpital",
        "hopital",
        "clinique",
        "urgences",
        "laboratoire",
        "pharmacie",
        "ehpad",
        "maison de retraite",
        # Adjacent
        "kinésithérapeute",
        "kinesitherapeute",
        "infirmier",
        "vétérinaire",
        "veterinaire",
        "mutuelle",
        "assurance",
        "logiciel médical",
        "logiciel medical",
        "recrutement",
    ],
    "ENRICH_INCLUDED_KEYWORDS": [],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [],
    "OUTSCRAPER_BATCH_SIZE": 40,
    "OUTSCRAPER_CONCURRENCY": 16,
    "OUTSCRAPER_LIMIT_PER_QUERY": 200,
    "OUTSCRAPER_POLL_INITIAL_S": 10,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 12,
    "OUTSCRAPER_ENRICHMENT": ["leads_n_contacts"],
    "OUTSCRAPER_EMAIL_RECOVERY_ENABLED": True,
    "TARGET_LEADS": 3000,
    "TARGET_MODE": "instantly_pushed",
    "SCRAPE_START_QUERY_PASS": 0,
    "SCRAPE_SKIP_PHASE_ENABLED": False,
    "SCRAPE_SKIP_SATURATION_TO_DEPARTMENT": True,
    "DUPLICATE_GEO_ADVANCE_RATE": 0.50,
    "SCRAPE_RELOAD_ENABLED": True,
    "SCRAPE_RELOAD_MAX_ROUNDS": 8,
    "SCRAPE_RELOAD_START_GEO_PHASE": "pass",
    "SCRAPE_RELOAD_START_QUERY_PASS": 0,
    "SCRAPE_CONTINUOUS_MODE": True,
    "SCRAPE_CONTINUOUS_MAX_ZERO_CYCLES": 3,
    "CONTINUOUS_KEYWORD_ROTATIONS": [
        [
            "médecin généraliste",
            "cabinet médical",
            "médecin de famille",
            "médecin traitant",
        ],
        [
            "medecin generaliste",
            "general practitioner",
            "family doctor",
            "docteur généraliste",
        ],
        [
            "médecin généraliste cabinet",
            "cabinet de médecine générale",
            "médecin traitant cabinet",
            "médecine générale",
        ],
        [
            "generaliste",
            "médecin libéral",
            "cabinet médical généraliste",
            "docteur medecin generaliste",
        ],
    ],
    "SERVICE_DEFAULT": "Médecine générale",
    "SERVICE_RULES": [],
    "KEYWORDS": [
        "médecin généraliste",
        "cabinet médical",
        "médecin de famille",
        "médecin traitant",
    ],
    "EXPANSION_KEYWORDS": [
        "general practitioner",
        "family doctor",
        "docteur généraliste",
        "médecine générale",
        "cabinet de médecine générale",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": False,
    "NICHE_METADATA": {
        "angle": "Lead gen pour médecins généralistes indépendants (Famille Marceau / JUM)",
        "valeur_client": "Prise de RDV étude fiscale DGFiP / AMF — cotisations CARMF, taxe 30–41 %",
        "effectif_cible": "cabinets indépendants",
    },
}

CONFIG = MEDECINS_GENERALISTES_CONFIG
