"""Restaurants indépendants (France) scraper preset — Outscraper taxonomy gate only (fast path)."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "restaurants_independants"
PRESET_LABEL = "Restaurants indépendants (France)"

_LIST_ID = "8ad641e7-3456-42df-9281-2c11f97df1c5"
_CAMPAIGN_ID = "e4f11e76-717e-4be9-a6ad-c7f0a331afb7"
_CAMPAIGN_ID_V2 = "2102110d-1491-4bd0-aa24-cfd29e9a0218"
_SUBSEQUENCE_ID = ""

RESTAURANTS_INDEPENDANTS_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_SUBSEQUENCE_ID": _SUBSEQUENCE_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID, _CAMPAIGN_ID_V2],
    "INSTANTLY_SKIP_IF_IN_CAMPAIGN": False,
    "INSTANTLY_SKIP_IF_IN_LIST": False,
    "INSTANTLY_PROVISION_LINKS": True,
    "LINK_PROVISION_CATEGORY": "jum",
    "ENRICH_ENABLED": False,
    "INGESTER_ENABLED": True,
    "INGESTER_MIN_SCORE": 0.55,
    "INGESTER_BORDERLINE_MIN": 0.35,
    "INGESTER_CONCURRENCY": 12,
    "INGESTER_FETCH_TIMEOUT": 8.0,
    "INGESTER_SIGNAL_WEIGHTS": {
        "taxonomy": 0.30,
        "website": 0.35,
        "review": 0.20,
        "registry": 0.15,
    },
    "INGESTER_REVIEW_ICP_KEYWORDS": [
        "restaurant",
        "brasserie",
        "bistrot",
        "cuisine",
        "menu",
        "carte",
        "chef",
        "repas",
        "déjeuner",
        "dîner",
    ],
    "INGESTER_REVIEW_ANTI_ICP_KEYWORDS": [
        "livraison uniquement",
        "dark kitchen",
        "franchise",
        "chaîne",
        "mcdonald",
        "kfc",
        "burger king",
        "logiciel",
        "plateforme",
    ],
    "OUTSCRAPER_FILTERS": ["only_with_website", "operational_only"],
    "TAXONOMY_GATE_ENABLED": True,
    "TAXONOMY_INCLUDED_KEYWORDS": [
        "restaurant",
        "brasserie",
        "bistrot",
        "restauration",
        "french restaurant",
        "restaurant traditionnel",
        "restaurant français",
        "gastronomique",
    ],
    "ENRICH_INCLUDED_KEYWORDS": [
        "restaurant",
        "brasserie",
        "bistrot",
        "cuisine",
        "menu",
        "carte",
        "réservation",
        "chef",
        "gastronomie",
        "terroir",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "franchise",
        "dark kitchen",
        "logiciel de caisse",
        "logiciel restauration",
        "plateforme de livraison",
        "recrutement",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "traiteur uniquement",
        "food truck",
        "livraison",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 16,
    "OUTSCRAPER_LIMIT_PER_QUERY": 50,
    "OUTSCRAPER_POLL_INITIAL_S": 10,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 300,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 3000,
    "TARGET_MODE": "instantly_pushed_run",
    "INSTANTLY_PUSH_EVERY": 25,
    "SERVICE_DEFAULT": "Restauration",
    "SERVICE_RULES": [],
    "KEYWORDS": [
        "restaurant",
        "restaurant traditionnel",
        "brasserie",
        "bistrot",
    ],
    "EXPANSION_KEYWORDS": [
        "restaurant gastronomique",
        "restaurant familial",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": False,
    "NICHE_METADATA": {
        "angle": "Lead gen pour restaurants indépendants",
        "valeur_client": "Prise de RDV avec des restaurateurs indépendants",
        "effectif_cible": "indépendant / petite équipe",
    },
}

CONFIG = RESTAURANTS_INDEPENDANTS_CONFIG
