"""Terrassement / VRD (France) scraper preset — Outscraper taxonomy gate (fast path)."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "terrassement_vrd"
PRESET_LABEL = "Terrassement / VRD (France)"

_LIST_ID = "d4bc89f7-b271-4ed7-9539-4ac968bfb7c9"
_CAMPAIGN_ID = "05bc06f8-4f60-4e6c-bae1-7afe30df38c7"
_SUBSEQUENCE_ID = ""

TERRASSEMENT_VRD_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_SUBSEQUENCE_ID": _SUBSEQUENCE_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID],
    "INSTANTLY_SKIP_IF_IN_CAMPAIGN": False,
    "INSTANTLY_SKIP_IF_IN_LIST": False,
    "INSTANTLY_PUSH_EVERY": 50,
    "INSTANTLY_PROVISION_LINKS": True,
    "LINK_PROVISION_CATEGORY": "jum",
    "ENRICH_ENABLED": False,
    "OUTSCRAPER_FILTERS": ["only_with_website", "operational_only"],
    # ── Taxonomy gate ──────────────────────────────────────────────────────────
    "TAXONOMY_GATE_ENABLED": True,
    "TAXONOMY_INCLUDED_KEYWORDS": [
        # Core niche
        "terrassement",
        "terrassier",
        "entreprise de terrassement",
        "travaux de terrassement",
        "vrd",
        "voirie et réseaux divers",
        "voirie",
        "travaux publics",
        # Networks & utilities
        "réseaux humides",
        "réseaux secs",
        "canalisation",
        "assainissement",
        "égout",
        "adduction",
        "distribution d'eau",
        "gaz",
        "électricité réseau",
        "fibre optique",
        "télécom",
        # Earthworks & site prep
        "nivellement",
        "déblai",
        "remblai",
        "compactage",
        "drainage",
        "fondations spéciales",
        "enrobé",
        "chaussée",
        "tranchée",
        "forage horizontal",
        "forage dirigé",
        # Google Maps category variants
        "entreprise de voirie",
        "entreprise d'assainissement",
        "entreprise de travaux publics",
        "génie civil",
    ],
    "TAXONOMY_HARD_EXCLUDED_KEYWORDS": [
        # Building trades (BTP général — hors scope VRD/terrassement)
        "plombier",
        "électricien",
        "maçon",
        "carreleur",
        "peintre en bâtiment",
        "couvreur",
        "menuisier",
        "charpentier",
        "chauffagiste",
        "plaquiste",
        "façadier",
        "isolation thermique",
        "constructeur de maisons",
        "rénovation intérieure",
        "second œuvre",
        # Material / equipment suppliers (not contractors)
        "magasin de matériaux",
        "négoce de matériaux",
        "grossiste en matériaux",
        "distributeur de matériaux",
        "fournisseur de matériaux",
        "quincaillerie",
        "point p",
        "location d'équipement",
        "location de matériel",
        "location d'engins",
        "location de nacelles",
        # Professional services / public sector
        "bureau d'études",
        "cabinet d'ingénierie",
        "ingénierie du bâtiment",
        "cabinet d'architecture",
        "architecte",
        "maître d'œuvre",
        "promoteur immobilier",
        "agence immobilière",
        "agent immobilier",
        "école",
        "centre de formation",
        "organisme de formation",
        "syndicat",
        "association",
        "administration",
        "collectivité",
        "assurance construction",
        "garantie décennale",
    ],
    "ENRICH_INCLUDED_KEYWORDS": [],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 16,
    "OUTSCRAPER_LIMIT_PER_QUERY": 50,
    "OUTSCRAPER_POLL_INITIAL_S": 10,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 300,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    # ── Geo expansion / reload ────────────────────────────────────────────────
    "SCRAPE_SKIP_PHASE_ENABLED": True,
    "SCRAPE_SKIP_SATURATION_TO_DEPARTMENT": True,
    "DUPLICATE_GEO_ADVANCE_RATE": 0.50,
    "SCRAPE_RELOAD_ENABLED": True,
    "SCRAPE_RELOAD_MAX_ROUNDS": 4,
    "SCRAPE_RELOAD_START_GEO_PHASE": "pass",
    "SCRAPE_RELOAD_START_QUERY_PASS": 0,
    # ── Target / pipeline ─────────────────────────────────────────────────────
    "TARGET_LEADS": 3000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Terrassement / VRD",
    "SERVICE_RULES": [],
    "KEYWORDS": [
        "terrassement",
        "entreprise VRD",
        "travaux publics",
        "voirie",
        "assainissement",
        "réseaux humides",
    ],
    "EXPANSION_KEYWORDS": [
        "terrassier",
        "canalisation",
        "réseaux secs",
        "nivellement",
        "enrobé",
        "forage dirigé",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": False,
    "NICHE_METADATA": {
        "angle": "Lead gen pour entreprises terrassement / VRD",
        "valeur_client": "Prise de RDV avec des entreprises de terrassement et voirie-réseaux",
        "effectif_cible": "PME spécialisées terrassement / VRD",
    },
}

CONFIG = TERRASSEMENT_VRD_CONFIG
